name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: npm install && npm run build
    - name: Deploy to GitHub Pages
      run: git push origin master:master
