name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: npm install && npm run build
    - name: Deploy to GitHub Pages
      run: 
        git config --global \"asurance\"
        git config --global \"784672616@qq.com\"
        git init
        git add .
        git commit -m \"auto deploy\"
        git push -f git@github.com:asurance/RayTracing.git master
