name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: npm install && npm run build
    - name: GitHub Pages Deploy
      env:
        BUILD_DIR: doc
      uses: maxheld83/ghpages@v0.2.1
